# Generated by Django 3.2.5 on 2021-07-30 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210730_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='line',
            name='price',
        ),
        migrations.AddField(
            model_name='line',
            name='extra_charges',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticketdetail',
            name='current_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trip',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='extra_charges',
            field=models.IntegerField(default=0),
        ),
    ]
