# Generated by Django 3.2.5 on 2021-08-07 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210730_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='trip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='app.trip'),
        ),
        migrations.AlterField(
            model_name='ticketdetail',
            name='ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_detail', to='app.ticket'),
        ),
    ]
