# Generated by Django 3.2.5 on 2021-08-07 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210807_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketdetail',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_detail', to='app.ticket'),
        ),
    ]
