# Generated by Django 3.2.5 on 2021-08-21 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210810_0104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='price',
            new_name='extra_changes',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='extra_charges',
            new_name='extra_changes',
        ),
        migrations.RemoveField(
            model_name='line',
            name='extra_charges',
        ),
        migrations.AddField(
            model_name='line',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=8),
        ),
    ]
