# Generated by Django 3.2.5 on 2021-08-22 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='line',
            unique_together={('start_point', 'end_point')},
        ),
    ]
